In [1]:
import sys

import sys
sys.path.insert(0,'..')

In [24]:
import leup
from leup import leup

In [25]:
import numpy as np
A = np.random.randn(5,4)
leup.leup(A)

AttributeError: 'function' object has no attribute 'leup'

In [26]:
np.random.seed(0)
m , n = 5, 4
A = np.random.randn(m,n)
A

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574]])

In [27]:
A[0] = 0 # causes issue
# A[:,0] = 0 # causes issue
# A[0,0] = 0 # works fine

In [29]:
L, E, U, P = leup(A)

In [30]:
np.linalg.norm(L @ E @ U @ P - A)

1.008410140090063e-15

In [31]:
E

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.86755799,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.35658492,  0.        ,  0.        ],
       [ 0.        ,  0.        , -0.22988862,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  2.62770777]])

In [32]:
from fractions import Fraction

In [33]:
M = np.zeros((5, 4), dtype=object)
M[0, 1] = Fraction(2, 3)
M[1, 0] = Fraction(3, 4)
L, E, U, P = leup(M)

In [37]:
E

array([[Fraction(2, 3), 0, 0, 0],
       [0, Fraction(3, 4), 0, 0],
       [0, 0, Fraction(0, 1), Fraction(0, 1)],
       [0, 0, Fraction(0, 1), Fraction(0, 1)],
       [0, 0, Fraction(0, 1), Fraction(0, 1)]], dtype=object)

In [48]:
def random_rational():
    x = np.random.rand()
    if x < 0.3:
        return Fraction(1,2)
    elif x < 0.5:
        return Fraction(2,3)
    elif x < 0.7:
        return Fraction(-3,4)
    else:
        return Fraction(1,1)

def random_rational_matrix(m, n, p=0.1):
    """
    m x n rational matrix
    every entry is non-zero with probability p
    """
    A = np.zeros((m,n), dtype=object)
    for i in range(m):
        for j in range(n):
            if np.random.rand() < p:
                A[i,j] = random_rational()
                
    return A

np.random.seed(0)
A = random_rational_matrix(5,4,0.2)
A

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, Fraction(1, 2), Fraction(1, 1)],
       [0, 0, 0, 0]], dtype=object)

In [50]:
L, E, U, P = leup(A)
(L @ E @ U @ P == A).all()

True

In [51]:
L @ E @ U @ P - A

array([[Fraction(0, 1), Fraction(0, 1), Fraction(0, 1), Fraction(0, 1)],
       [Fraction(0, 1), Fraction(0, 1), Fraction(0, 1), Fraction(0, 1)],
       [Fraction(0, 1), Fraction(0, 1), Fraction(0, 1), Fraction(0, 1)],
       [Fraction(0, 1), Fraction(0, 1), Fraction(0, 1), Fraction(0, 1)],
       [Fraction(0, 1), Fraction(0, 1), Fraction(0, 1), Fraction(0, 1)]],
      dtype=object)